/**
 * Curated overrides for fields hard to extract from Wikidata: motto
 * translations (when motto is non-English), former_capitals, former_names,
 * currency unicode symbols. Source: Wikipedia infoboxes (CC BY-SA 4.0).
 * Keyed by ISO 3166-1 alpha-2.
 */
module.exports = {
  IN: { motto_translation: 'Truth alone triumphs', former_capitals: ['Calcutta (1858-1911)'], currency_symbol: '₹' },
  US: { former_capitals: ['Philadelphia (1790-1800)', 'New York City (1785-1790)'], currency_symbol: '$' },
  GB: { motto_translation: 'God and my right', currency_symbol: '£' },
  FR: { motto_translation: 'Liberty, Equality, Fraternity', currency_symbol: '€' },
  DE: { motto_translation: 'Unity and Justice and Freedom', currency_symbol: '€' },
  IT: { currency_symbol: '€' },
  ES: { motto_translation: 'Further beyond', currency_symbol: '€' },
  PT: { currency_symbol: '€' },
  NL: { motto_translation: 'I will maintain', currency_symbol: '€' },
  BE: { motto_translation: 'Unity makes strength', currency_symbol: '€' },
  CH: { motto_translation: 'One for all, all for one', currency_symbol: 'CHF' },
  AT: { currency_symbol: '€' },
  GR: { motto_translation: 'Freedom or Death', currency_symbol: '€' },
  IE: { currency_symbol: '€' },
  FI: { currency_symbol: '€' },
  SE: { motto_translation: 'For Sweden, With the Times', currency_symbol: 'kr' },
  NO: { motto_translation: 'All for Norway', currency_symbol: 'kr' },
  DK: { motto_translation: 'Gods help, the love of the people, Denmarks strength', currency_symbol: 'kr' },
  IS: { currency_symbol: 'kr' },
  PL: { currency_symbol: 'zł' },
  CZ: { motto_translation: 'Truth prevails', currency_symbol: 'Kč', former_names: ['Czechoslovakia (1918-1992)', 'Bohemia and Moravia'] },
  SK: { currency_symbol: '€', former_names: ['Czechoslovakia (1918-1992)'] },
  HU: { currency_symbol: 'Ft' },
  RO: { currency_symbol: 'lei' },
  BG: { motto_translation: 'Unity makes strength', currency_symbol: 'лв' },
  HR: { currency_symbol: '€', former_names: ['Yugoslavia (1918-1991)'] },
  SI: { currency_symbol: '€', former_names: ['Yugoslavia (1918-1991)'] },
  RS: { motto_translation: 'Only Unity Saves the Serbs', former_names: ['Yugoslavia (1918-2003)', 'Serbia and Montenegro (2003-2006)'] },
  BA: { former_names: ['Yugoslavia (1918-1992)'] },
  ME: { currency_symbol: '€', former_names: ['Serbia and Montenegro (2003-2006)'] },
  MK: { former_names: ['Yugoslavia (1944-1991)', 'Republic of Macedonia (1991-2019)'] },
  AL: { motto_translation: 'You, Albania, give me honor, give me the name Albanian' },
  XK: { currency_symbol: '€', former_names: ['Yugoslavia (until 1999)', 'UN-administered (1999-2008)'] },
  RU: { currency_symbol: '₽', former_names: ['Soviet Union (1922-1991)', 'Russian Empire (until 1917)'], former_capitals: ['Saint Petersburg (1712-1918)'] },
  UA: { currency_symbol: '₴', former_names: ['Ukrainian SSR (Soviet Union)'], former_capitals: ['Kharkiv (1919-1934)'] },
  BY: { former_names: ['Byelorussian SSR (Soviet Union)'] },
  LT: { currency_symbol: '€', former_names: ['Soviet Union (1940-1990)'], former_capitals: ['Kaunas (1920-1939)'] },
  LV: { currency_symbol: '€', former_names: ['Soviet Union (1940-1991)'] },
  EE: { currency_symbol: '€', former_names: ['Soviet Union (1940-1991)'] },
  MD: { former_names: ['Moldavian SSR (Soviet Union)'] },
  GE: { motto_translation: 'Strength is in Unity', former_names: ['Soviet Union (1921-1991)'] },
  AM: { former_names: ['Soviet Union (1922-1991)'] },
  AZ: { former_names: ['Soviet Union (1920-1991)'] },
  KZ: { former_names: ['Soviet Union (1936-1991)'], former_capitals: ['Almaty (1929-1997)'] },
  UZ: { former_names: ['Soviet Union (1924-1991)'], former_capitals: ['Samarkand (1925-1930)'] },
  KG: { former_names: ['Soviet Union (1936-1991)'] },
  TJ: { former_names: ['Soviet Union (1929-1991)'] },
  TM: { former_names: ['Soviet Union (1924-1991)'] },
  CN: { currency_symbol: '¥', former_names: ['Republic of China (1912-1949)', 'Qing dynasty (until 1912)'], former_capitals: ['Nanjing (1928-1949, briefly)'] },
  JP: { currency_symbol: '¥', former_capitals: ['Kyoto (794-1868)', 'Nara (710-794)'] },
  KR: { currency_symbol: '₩', former_capitals: ['Busan (1950-1953, wartime)'] },
  KP: { motto_translation: 'Prosperous and Powerful Country', currency_symbol: '₩' },
  TW: { currency_symbol: 'NT$', former_names: ['Republic of China (since 1912; effective territory Taiwan since 1949)', 'Formosa (historical)'] },
  VN: { motto_translation: 'Independence, Freedom, Happiness', currency_symbol: '₫', former_names: ['Republic of Vietnam (South, until 1975)', 'Democratic Republic of Vietnam (North, until 1976)'], former_capitals: ['Saigon (South Vietnam capital, until 1975)'] },
  TH: { currency_symbol: '฿', former_names: ['Siam (until 1939, 1945-1949)'] },
  ID: { motto_translation: 'Unity in Diversity', currency_symbol: 'Rp', former_names: ['Dutch East Indies (until 1945)'] },
  MY: { motto_translation: 'Unity is Strength', currency_symbol: 'RM', former_names: ['Federation of Malaya (1948-1963)'] },
  SG: { motto_translation: 'Onward Singapore', currency_symbol: 'S$', former_names: ['Part of Malaysia (1963-1965)', 'Straits Settlements (until 1946)'] },
  PH: { motto_translation: 'For God, People, Nature, and Country', currency_symbol: '₱' },
  MM: { currency_symbol: 'K', former_names: ['Burma (until 1989)'], former_capitals: ['Yangon / Rangoon (until 2006)'] },
  KH: { motto_translation: 'Nation, Religion, King', currency_symbol: '៛', former_names: ['Kampuchea (1975-1989)'] },
  LA: { motto_translation: 'Peace, Independence, Democracy, Unity, Prosperity', currency_symbol: '₭' },
  LK: { former_names: ['Ceylon (until 1972)'], former_capitals: ['Colombo (executive capital still)'] },
  BD: { currency_symbol: '৳', former_names: ['East Pakistan (1947-1971)', 'East Bengal (part of British India)'] },
  PK: { motto_translation: 'Faith, Unity, Discipline', currency_symbol: '₨', former_capitals: ['Karachi (1947-1959)', 'Rawalpindi (1959-1966, interim)'] },
  NP: { currency_symbol: '₨', former_names: ['Kingdom of Nepal (until 2008)'] },
  BT: { currency_symbol: 'Nu.' },
  AF: { motto_translation: 'There is no god but God; Muhammad is the messenger of God', currency_symbol: '؋', former_names: ['Islamic Republic of Afghanistan (2004-2021)', 'Kingdom of Afghanistan (until 1973)'] },
  IR: { motto_translation: 'Independence, Freedom, Islamic Republic', currency_symbol: '﷼', former_names: ['Persia (officially until 1935)', 'Imperial State of Iran (until 1979)'] },
  IQ: { motto_translation: 'God is the Greatest' },
  SY: { currency_symbol: '£', former_names: ['United Arab Republic (1958-1961, with Egypt)'] },
  LB: { currency_symbol: '£' },
  JO: { former_names: ['Transjordan (until 1949)'] },
  IL: { currency_symbol: '₪' },
  PS: { currency_symbol: '₪' },
  SA: { motto_translation: 'There is no god but God; Muhammad is the messenger of God', currency_symbol: '﷼', former_names: ['Kingdom of Hejaz and Nejd (until 1932)'] },
  AE: { former_names: ['Trucial States (until 1971)'] },
  YE: { currency_symbol: '﷼', former_names: ['North Yemen + South Yemen (until 1990 unification)'] },
  TR: { motto_translation: 'Peace at Home, Peace in the World', currency_symbol: '₺', former_names: ['Ottoman Empire (until 1922)'], former_capitals: ['Istanbul / Constantinople (until 1923)'] },
  EG: { currency_symbol: 'E£', former_names: ['United Arab Republic (1958-1971)'] },
  LY: { motto_translation: 'God is the Greatest' },
  TN: { motto_translation: 'Freedom, Dignity, Justice, Order' },
  DZ: { motto_translation: 'By the people and for the people' },
  MA: { motto_translation: 'God, Country, King' },
  SD: { motto_translation: 'Victory is from God' },
  SS: { motto_translation: 'Justice, Liberty, Prosperity', former_names: ['Part of Sudan (until 2011)'] },
  ET: { currency_symbol: 'Br', former_names: ['Abyssinia (historical)', 'Derg / PDRE (1974-1991)'] },
  ER: { former_names: ['Part of Ethiopia (until 1993)'] },
  KE: { motto_translation: 'Let us all pull together', currency_symbol: 'KSh' },
  TZ: { motto_translation: 'Freedom and Unity', currency_symbol: 'TSh', former_names: ['Tanganyika + Zanzibar (until 1964 union)'] },
  UG: { currency_symbol: 'USh' },
  RW: { motto_translation: 'Unity, Work, Patriotism' },
  BI: { motto_translation: 'Unity, Work, Progress' },
  CD: { motto_translation: 'Justice, Peace, Work', former_names: ['Zaire (1971-1997)', 'Belgian Congo (until 1960)'] },
  CG: { motto_translation: 'Unity, Work, Progress' },
  CM: { motto_translation: 'Peace, Work, Fatherland' },
  NG: { currency_symbol: '₦', former_capitals: ['Lagos (until 1991)'] },
  GH: { currency_symbol: '₵', former_names: ['Gold Coast (until 1957)'] },
  ZA: { motto_translation: 'Unity in Diversity', currency_symbol: 'R' },
  ZW: { former_names: ['Rhodesia (until 1980)', 'Southern Rhodesia (until 1965)'] },
  ZM: { motto_translation: 'One Zambia, One Nation', former_names: ['Northern Rhodesia (until 1964)'] },
  MW: { motto_translation: 'Unity and Freedom', former_names: ['Nyasaland (until 1964)'] },
  MZ: { currency_symbol: 'MT' },
  AO: { currency_symbol: 'Kz' },
  NA: { motto_translation: 'Unity, Liberty, Justice', former_names: ['South West Africa (until 1990)'] },
  BW: { motto_translation: 'Rain', former_names: ['Bechuanaland Protectorate (until 1966)'] },
  CA: { motto_translation: 'From sea to sea', currency_symbol: 'C$' },
  MX: { currency_symbol: '$' },
  BR: { motto_translation: 'Order and Progress', currency_symbol: 'R$', former_capitals: ['Rio de Janeiro (1763-1960)', 'Salvador (1549-1763)'] },
  AR: { motto_translation: 'In Union and Liberty', currency_symbol: '$' },
  CL: { motto_translation: 'By reason or by force', currency_symbol: '$' },
  CO: { motto_translation: 'Freedom and Order', currency_symbol: '$' },
  PE: { motto_translation: 'Firm and Happy for the Union', currency_symbol: 'S/' },
  VE: { currency_symbol: 'Bs.' },
  EC: { currency_symbol: '$' },
  BO: { currency_symbol: 'Bs.' },
  PY: { motto_translation: 'Peace and Justice', currency_symbol: '₲' },
  UY: { motto_translation: 'Freedom or Death', currency_symbol: '$U' },
  CR: { motto_translation: 'Long live work', currency_symbol: '₡' },
  PA: { motto_translation: 'For the benefit of the world' },
  NI: { motto_translation: 'In God We Trust', currency_symbol: 'C$' },
  HN: { motto_translation: 'Free, sovereign, independent', currency_symbol: 'L' },
  GT: { motto_translation: 'Grow free and fertile', currency_symbol: 'Q' },
  SV: { motto_translation: 'God, Union, Liberty' },
  BZ: { motto_translation: 'I flourish in the shade', former_names: ['British Honduras (until 1973)'] },
  CU: { motto_translation: 'Fatherland or Death', currency_symbol: '₱' },
  HT: { motto_translation: 'Unity makes strength', currency_symbol: 'G' },
  DO: { motto_translation: 'God, Country, Liberty' },
  JM: { currency_symbol: 'J$' },
  AU: { currency_symbol: 'A$', former_capitals: ['Melbourne (1901-1927, provisional)'] },
  NZ: { currency_symbol: 'NZ$', former_names: ['Dominion of New Zealand (1907-1947)'] },
  FJ: { motto_translation: 'Fear God and honour the Queen' },
  PG: { motto_translation: 'Unity in Diversity' },
  WS: { motto_translation: 'God is the foundation of Samoa', former_names: ['Western Samoa (until 1997)'] },
  CY: { currency_symbol: '€' },
  MT: { currency_symbol: '€' },
  LU: { currency_symbol: '€' },
};
